### ISSUE TITLE
darter.core.ParseError: (20532, "Version (8ee4ef7a67df9845fba331734198a953) doesn't match with the one this parser was made for")

### ISSUE THREAD

**Issue by BadDeveloper2022** [mildsunrise/darter#4]
[Header]
  File "G:\darter-master\darter\file.py", line 44, in parse_elf_snapshot
  length = 5094
    vm=True, **kwargs).parse()
  kind = 2 ('kFullAOT', 'Full + AOT code')
  File "G:\darter-master\darter\core.py", line 230, in parse

    self.parse_header()
[00005034]: WARN: An inconsistency was found; failing. Pass strict=False to treat inconsistencies as warnings and continue parsing.
  File "G:\darter-master\darter\core.py", line 327, in parse_header
    self.warning('Version ({}) doesn\'t match with the one this parser was made for'.format(self.version))
  File "G:\darter-master\darter\core.py", line 286, in warning
    raise ParseError(self.data_offset + self.data.tell(), message)
darter.core.ParseError: (20532, "Version (8ee4ef7a67df9845fba331734198a953) doesn't match with the one this parser was made for")

-------------------------------------------------------------------------------------
Hello
Is this a matter of procedure?
Not compatible with this version?

**Comment by BadDeveloper2022** [comment]
ILLEGAL = 0
	FREE_LIST_ELEMENT = 1
	FORWARDING_CORPSE = 2
	OBJECT = 3
	CLASS = 4
	PATCH_CLASS = 5
	FUNCTION = 6
	CLOSURE_DATA = 7
	SIGNATURE_DATA = 8
	REDIRECTION_DATA = 9
	FFI_TRAMPOLINE_DATA = 10
	FIELD = 11
	SCRIPT = 12
	LIBRARY = 13
	NAMESPACE = 14
	KERNEL_PROGRAM_INFO = 15
	CODE = 16
	BYTECODE = 17
	INSTRUCTIONS = 18
	INSTRUCTIONS_SECTION = 19
	OBJECT_POOL = 20
	PC_DESCRIPTORS = 21
	CODE_SOURCE_MAP = 22
	COMPRESSED_STACK_MAPS = 23
	LOCAL_VAR_DESCRIPTORS = 24
	EXCEPTION_HANDLERS = 25
	CONTEXT = 26
	CONTEXT_SCOPE = 27
	PARAMTER_TYPE_CHECK = 28
	SINGLE_TARGET_CACHE = 29
	UNLINKED_CALL = 30
	MONOMORPHIC_SMIABLE = 31
	CALL_SITE_DATA = 32
	IC_DATA = 33
	MEGAMORPHIC_CACHE = 34
	SUBTYPE_TEST_CACHE = 35
	LOADING_UNIT = 36
	ERROR = 37
	API_ERROR = 38
	LANGUAGE_ERROR = 39
	UNHANDLED_EXCEPTION = 40
	UNWIND_ERROR = 41
	INSTANCE = 42
	LIBRARY_PREFIX = 43
	TYPE_ARGUMENTS = 44
	ABSTRACT_TYPE = 45
	TYPE = 46
	TYPE_REF = 47
	TYPE_PARAMETER = 48
	CLOSURE = 49
	NUMBER = 50
	INTEGER = 51
	SMI = 52
	MINT = 53
	DOUBLE = 54
	BOOL = 55
	GROWABLE_OBJECT_ARRAY = 56
	FLOAT_32X4 = 57
	INT_32X4 = 58
	FLOAT_64X2 = 59
	TYPED_DATA_BASE = 60
	TYPED_DATA = 61
	EXTERNAL_TYPED_DATA = 62
	TYPED_DATA_VIEW = 63
	POINTER = 64
	DYNAMIC_LIBRARY = 65
	CAPABILITY = 66
	RECEIVE_PORT = 67
	SEND_PORT = 68
	STACK_TRACE = 69
	REGEX = 70
	WEAK_PROPERTY = 71
	MIRROR_REFERENCE = 72
	LINKED_HASHMAP = 73
	FUTURE_OR = 74
	USER_TAG = 75
	TRANSFERABLE_TYPED_DATA = 76
	WEAK_SERIALIZATION_REFERENCE = 77
	ARRAY = 78
	IMMUTABLE_ARRAY = 79
	STRING = 80
	ONE_BYTE_STRING = 81
	TWO_BYTE_STRING = 82
	EXTERNAL_ONE_BYTE_STRING = 83
	EXTERNAL_TWO_BYTE_STRING = 84
	FFI_POINTER = 85
	FFI_NATIVE_FUNCTION = 86
	FFI_INT8 = 87
	FFI_INT16 = 88
	FFI_INT32 = 89
	FFI_INT64 = 90
	FFI_UINT8 = 91
	FFI_UINT16 = 92
	FFI_UINT32 = 93
	FFI_UINT64 = 94
	FFI_INT_PTR = 95
	FFI_FLOAT = 96
	FFI_DOUBLE = 97
	FFI_VOID = 98
	FFI_HANDLE = 99
	FFI_NATIVE_TYPE = 100
	FFI_DYNAMIC_LIBRARY = 101
	FFI_STRUCT = 102
	WASM_INT32 = 103
	WASM_INT64 = 104
	WASM_FLOAT = 105
	WASM_DOUBLE = 106
	WASM_VOID = 107
	TYPED_DATA_INT8_ARRAY = 108
	TYPED_DATA_INT8_ARRAY_VIEW = 109
	EXTERNAL_TYPED_DATA_INT8_ARRAY = 110
	TYPED_DATA_UINT8_ARRAY = 111
	TYPED_DATA_UINT8_ARRAY_VIEW = 112
	EXTERNAL_TYPED_DATA_UINT8_ARRAY = 113
	TYPED_DATA_UINT8_CLAMPED_ARRAY = 114
	TYPED_DATA_UINT8_CLAMPED_ARRAY_VIEW = 115
	EXTERNAL_TYPED_DATA_UINT8_CLAMPED_ARRAY = 116
	TYPED_DATA_INT16_ARRAY = 117
	TYPED_DATA_INT16_ARRAY_VIEW = 118
	EXTERNAL_TYPED_DATA_INT16_ARRAY = 119
	TYPED_DATA_UINT16_ARRAY = 120
	TYPED_DATA_UINT16_ARRAY_VIEW = 121
	EXTERNAL_TYPED_DATA_UINT16_ARRAY = 122
	TYPED_DATA_INT32_ARRAY = 123
	TYPED_DATA_INT32_ARRAY_VIEW = 124
	EXTERNAL_TYPED_INT32_ARRAY = 125
	TYPED_DATA_UINT32_ARRAY = 126
	TYPED_DATA_UINT32_ARRAY_VIEW = 127
	EXTERNAL_TYPED_DATA_UINT32_ARRAY = 128
	TYPED_DATA_INT64_ARRAY = 129
	TYPED_DATA_INT64_ARRAY_VIEW = 130
	EXTERNAL_TYPED_DATA_INT64_ARRAY = 131
	TYPED_DATA_UINT64_ARRAY = 132
	TYPED_DATA_UINT64_ARRAY_VIEW = 133
	EXTERNAL_TYPED_DATA_UINT64_ARRAY = 134
	TYPED_DATA_FLOAT32_ARRAY = 135
	TYPED_DATA_FLOAT32_ARRAY_VIEW = 136
	EXTERNAL_TYPED_DATA_FLOAT32_ARRAY = 137
	TYPED_DATA_FLOAT64_ARRAY = 138
	TYPED_DATA_FLOAT64_ARRAY_VIEW = 139
	EXTERNAL_TYPED_DATA_FLOAT64_ARRAY = 140
	TYPED_DATA_FLOAT32X4_ARRAY = 141
	TYPED_DATA_FLOAT32X4_ARRAY_VIEW = 142
	EXTERNAL_TYPED_DATA_FLOAT32X4_ARRAY = 143
	TYPED_DATA_INT32X4_ARRAY = 144
	TYPED_DATA_INT32X4_ARRAY_VIEW = 145
	EXTERNAL_TYPED_DATA_INT32X4_ARRAY = 146
	TYPED_DATA_FLOAT64X2_ARRAY = 147
	TYPED_DATA_FLOAT64X2_ARRAY_VIEW = 148
	EXTERNAL_TYPED_DATA_FLOAT64X2_ARRAY = 149
	BYTE_DATA_VIEW = 150
	BYTE_BUFFER = 151
	NULL = 152
	DYNAMIC = 153
	VOID = 154
	NEVER = 155
	NUM_PREDEFINED = 156

-------------------
classids for 8ee4ef7a67df9845fba331734198a953

**Comment by BadDeveloper2022** [comment]
this is youer classids
["Illegal", "Stack", "kFreeListElement", "kForwardingCorpse", "Object", "Class", "PatchClass", "Function", "ClosureData", "SignatureData", "RedirectionData", "FfiTrampolineData", "Field", "Script", "Library", "Namespace", "KernelProgramInfo", "Code", "Bytecode", "Instructions", "ObjectPool", "PcDescriptors", "CodeSourceMap", "StackMap", "LocalVarDescriptors", "ExceptionHandlers", "Context", "ContextScope", "ParameterTypeCheck", "SingleTargetCache", "UnlinkedCall", "ICData", "MegamorphicCache", "SubtypeTestCache", "Error", "ApiError", "LanguageError", "UnhandledException", "UnwindError", "Instance", "LibraryPrefix", "TypeArguments", "AbstractType", "Type", "TypeRef", "TypeParameter", "Closure", "Number", "Integer", "Smi", "Mint", "Double", "Bool", "GrowableObjectArray", "Float32x4", "Int32x4", "Float64x2", "TypedDataBase", "TypedData", "ExternalTypedData", "TypedDataView", "Pointer", "DynamicLibrary", "Capability", "ReceivePort", "SendPort", "StackTrace", "RegExp", "WeakProperty", "MirrorReference", "LinkedHashMap", "UserTag", "TransferableTypedData", "Array", "ImmutableArray", "String", "OneByteString", "TwoByteString", "ExternalOneByteString", "ExternalTwoByteString", "FfiPointer", "FfiNativeFunction", "FfiInt8", "FfiInt16", "FfiInt32", "FfiInt64", "FfiUint8", "FfiUint16", "FfiUint32", "FfiUint64", "FfiIntPtr", "FfiFloat", "FfiDouble", "FfiVoid", "FfiNativeType", "FfiDynamicLibrary", "FfiStruct", "TypedDataInt8Array", "TypedDataInt8ArrayView", "ExternalTypedDataInt8Array", "TypedDataUint8Array", "TypedDataUint8ArrayView", "ExternalTypedDataUint8Array", "TypedDataUint8ClampedArray", "TypedDataUint8ClampedArrayView", "ExternalTypedDataUint8ClampedArray", "TypedDataInt16Array", "TypedDataInt16ArrayView", "ExternalTypedDataInt16Array", "TypedDataUint16Array", "TypedDataUint16ArrayView", "ExternalTypedDataUint16Array", "TypedDataInt32Array", "TypedDataInt32ArrayView", "ExternalTypedDataInt32Array", "TypedDataUint32Array", "TypedDataUint32ArrayView", "ExternalTypedDataUint32Array", "TypedDataInt64Array", "TypedDataInt64ArrayView", "ExternalTypedDataInt64Array", "TypedDataUint64Array", "TypedDataUint64ArrayView", "ExternalTypedDataUint64Array", "TypedDataFloat32Array", "TypedDataFloat32ArrayView", "ExternalTypedDataFloat32Array", "TypedDataFloat64Array", "TypedDataFloat64ArrayView", "ExternalTypedDataFloat64Array", "TypedDataFloat32x4Array", "TypedDataFloat32x4ArrayView", "ExternalTypedDataFloat32x4Array", "TypedDataInt32x4Array", "TypedDataInt32x4ArrayView", "ExternalTypedDataInt32x4Array", "TypedDataFloat64x2Array", "TypedDataFloat64x2ArrayView", "ExternalTypedDataFloat64x2Array", "ByteDataView", "ByteBuffer", "Null", "Dynamic", "Void"]

**Comment by mildsunrise** [comment]
yes, it's not (yet) compatible with this version. see the [Status section](https://github.com/mildsunrise/darter#status) in the README and the comments at #3. I'll close this as a dupe
