### ISSUE TITLE
how can I find a function for disassember?

### ISSUE THREAD

**Issue by alexcohn** [mildsunrise/darter#6]
I have a flutter app with `libs/armeabi-v7a/libapp.so`, and there I am looking for a function (?) `hexEncode`. This is how it looks in the 'dictionary':
````
.rodata:00D6AC67                                  db 0, '8', 3, 'Q', 0, 12h, 0, 0, 0
.rodata:00D6AC70  aL_vwhexEncode  db "l\tvwhexEncode",0
.rodata:00D6AC7E                                  db 0, 0
.rodata:00D6AC80                                  db '8', 4, 'Q', 0, 1Ch, 0, 0, 0, A8h, 83h, B6h
````
Can **darter** help me to find the code of this function?

**Comment by mildsunrise** [comment]
it seems you're in luck, your app doesn't have obfuscation turned on.
so if by code you mean the AOT assembly, then yes. look for `hexEncode` in the strings table, then look at its backreferences like the notebook shows. you can obtain the address & size of the function from the `Code` object.

**Comment by mildsunrise** [comment]
however be aware darter is old and the snapshot format is constantly changing. there's substantial chance it won't be able to parse your snapshot without fixes. I want to get it to support more Dart versions but it takes time
